require "atlantica_online_craft_calculator_engine/engine"
require 'atlantica_online_craft_calculator_engine/integer_extractor'

require 'atlantica_online_craft_calculator'

module AtlanticaOnlineCraftCalculatorEngine
end
